import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import Nifty from '../components/Nifty'

export default function Home() {
  return (
    <div>
      <Head>
        <title>GeekSeed2.0</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Stock Analysis' message='' />
      <Slider slides={SliderData} />
      <Nifty></Nifty>
      <footer className="bg-gray-200 text-center lg:text-left">
        <div className="text-blue-100 text-center p-4" style={{backgroundColor: "black",opacity:0.2,}}>
          © 2023 Copyright: GeekSeed 2.0
          
        </div>
      </footer>
      
    </div>
  );
}
